const
    SET_LOADING = 'SET_LOADING',
    SET_USERS = 'SET_USERS',
    RESET_USERS = 'RESET_USERS',
    SET_PROFILE = 'SET_PROFILE',
    SET_REPOS = 'SET_REPOS',
    SET_ALERT = 'SET_ALERT',
    RESET_ALERT = 'RESET_ALERT';

export { SET_LOADING, SET_USERS, RESET_USERS, SET_PROFILE, SET_REPOS, SET_ALERT, RESET_ALERT };